---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-python
  labels:
    app.kubernetes.io/name: "test-python"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "test-python"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "test-python"

    spec:
      containers:
        - name: "test-python"
          image: "frontimg:latest"
          imagePullPolicy: "Never"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
