apiVersion: v1
kind: Service
metadata:
  name: test-python
  labels:
    app.kubernetes.io/name: "test-python"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "test-python"
